### ISSUE TITLE
Ensemble details

### ISSUE THREAD

**Issue by idansc** [jnhwkim/ban-vqa#10]
Hi, thanks for the library. 
Is it possible to share details of your ensemble method?

**Comment by jnhwkim** [comment]
Hi, Idan. Roughly speaking, we use 15 BAN+Glove+Counter models, where 10 models use Visual Genome for data augmentation and the other 5 models are only trained using `train` and `val` splits. All models have different random seeds. 
Since I believe this method is too naive, so I want to draw attention to @YuJiang01's [technical report](http://arxiv.org/abs/1807.09956) about their 1st entry in 2018 VQA Challenge.
