### ISSUE TITLE
Evaluating accuracy on test?

### ISSUE THREAD

**Issue by HuyRyu** [jnhwkim/ban-vqa#3]
When I run python3 test.py --label mytest, i got a warning 'RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greately increasing memory usage. To compact weights again call flatten_parameters().' and code still complete but the result was evaluated on VQA challenge only 1% for overall. I use the your pretrained model and feature.

**Comment by jnhwkim** [comment]
Warning message should not affect the result. I have checked the reproduction of the result, so I kindly recommend you to check the procedure. My hunch is your vocabulary cache is not matched with our pretrained model. Let me know if the issue is still persistent. 

See the last section of [this script](https://github.com/jnhwkim/ban-vqa/blob/master/tools/download.sh).

**Comment by HuyRyu** [comment]
It done, thank you very much.
