### ISSUE TITLE
where to find "val_flickr30k_resnet101_faster_rcnn_genome.tsv.3"?

### ISSUE THREAD

**Issue by ziyanyang** [jnhwkim/ban-vqa#43]
Hi,

I downloaded flickr30k_features.zip from https://drive.google.com/file/d/1BmcxeY1kXzMZv54d4wMtl7HGc8Cs9zgO/view?usp=sharing but all the tsv files are not in this zip file. Where can I get them? Also, why there exist train/val/test.hdf5 files in this zip file? I thought these files should be generated through adaptive_detection_features_converter.py.

**Comment by jnhwkim** [comment]
Sorry for your confusion. Although my memory is fading away due to catastrophic forgetting, I did not keep the tsv files from the converter but hdf5 files for the reproduction of the numbers of the paper. Unfortunately, if you need the tsv files, you should regenerate for your own. Sorry for that. 😥

**Comment by ziyanyang** [comment]
> Sorry for your confusion. Although my memory is fading away due to catastrophic forgetting, I did not keep the tsv files from the converter but hdf5 files for the reproduction of the numbers of the paper. Unfortunately, if you need the tsv files, you should regenerate for your own. Sorry for that. 😥

Therefore, are the hdf5 files in the downloaded flickr30k_features.zip used to reproduce the results? I don't need the tsv files but I do need the features and bounding boxes for flickr 30k validation/testing sets.
